crab status -d crab_DY
crab status -d crab_WA
crab status -d crab_WWA
crab status -d crab_WWW
crab status -d crab_WWZ
crab status -d crab_WZA
crab status -d crab_WZZ
crab status -d crab_WZto2L
crab status -d crab_WZto3L
crab status -d crab_ZA
crab status -d crab_ZZ
crab status -d crab_ZZZ
crab status -d crab_ggZZ
crab status -d crab_tZq
crab status -d crab_ttA
crab status -d crab_ttJets
crab status -d crab_ttW
crab status -d crab_ttZ
crab status -d crab_DoubleMuon_B
crab status -d crab_DoubleMuon_C
crab status -d crab_DoubleMuon_D
crab status -d crab_DoubleMuon_E
crab status -d crab_DoubleMuon_F
