crab kill -d crab_DoubleEG_B
crab kill -d crab_DoubleEG_C
crab kill -d crab_DoubleEG_D
crab kill -d crab_DoubleEG_E
crab kill -d crab_DoubleEG_F
crab kill -d crab_DoubleMuon_B
crab kill -d crab_DoubleMuon_C
crab kill -d crab_DoubleMuon_D
crab kill -d crab_DoubleMuon_E
crab kill -d crab_DoubleMuon_F
crab kill -d crab_DoubleEG_B
crab kill -d crab_DoubleEG_C
crab kill -d crab_DoubleEG_D
crab kill -d crab_DoubleEG_E
crab kill -d crab_DoubleEG_F
crab kill -d crab_MuonEG_B
crab kill -d crab_MuonEG_C
crab kill -d crab_MuonEG_D
crab kill -d crab_MuonEG_E
crab kill -d crab_MuonEG_F
crab kill -d crab_SingleEG_B
crab kill -d crab_SingleEG_C
crab kill -d crab_SingleEG_D
crab kill -d crab_SingleEG_E
crab kill -d crab_SingleEG_F
